name: E2E testes - mentoria

# gatilhos
on:
  workflow_dispatch:

jobs: 
  tests:
  
    #  [config do Sistema operacional] (windows/linux/mac, chrome/firefox/edge, ...) 
    runs-on: ubuntu-latest
    
    # [variaveis] (variáveis de ambiente, chaves de acesso a plataformas, etc.)
    env: 
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000

    #  [acoes ou passos]
    steps:
      - name: checkout do Repositorio
        uses: actions/checkout@v4

      - name: Instalando as dependencias
        run: npm install

      - name: Iniciando o servidor de mocks
        run: npm run mock-server &
        
      - name: Iniciando o servidor de aplicacao
        run: npm run server &

      - name: Executar os testes
        run: npx cypress run
      
        





      
    
